### ISSUE TITLE
Little typo and some questions on the code?

### ISSUE THREAD

**Issue by ykchong45** [mhyousefi/MIPS-pipeline-processor#1]
1. https://github.com/mhyousefi/MIPS-pipeline-processor/blob/fefa3336fba8b1bcbf60c0d2022d6910ef80c0e6/modules/pipeStages/IDStage.v#L20
Should it be an **output**? Reference here:
https://github.com/mhyousefi/MIPS-pipeline-processor/blob/fefa3336fba8b1bcbf60c0d2022d6910ef80c0e6/modules/controlUnit/controller.v#L6

2. In the comment there's a little typo, "of" should be changed to "or" :https://github.com/mhyousefi/MIPS-pipeline-processor/blob/fefa3336fba8b1bcbf60c0d2022d6910ef80c0e6/modules/pipeStages/IDStage.v#L39

**Comment by mhyousefi** [comment]
Hi, sorry for the delay.
You are right about the typo; it was fixed.
About the first point, even though `branchEn` is not the output of a sequential circuit (the controller is combinational), it is assigned in an `always` statement. And as such, needs to be of type `output reg`. But keep in mind, the code described under an `always@(*)` statement will be synthesized to a purely combinational circuit.
