### ISSUE TITLE
Backward Taken and Forward Not TakenBranch Prediction

### ISSUE THREAD

**Issue by umutdag1** [mhyousefi/MIPS-pipeline-processor#2]
Hello Guys,
I wanna this implementation in IF Stage. I don't know how to do it. Can you show me the way how to implement it in IF Stage ?

**Comment by berkay97** [comment]
update

@mhyousefi

**Comment by mhyousefi** [comment]
@umutdag1 
@berkay97 

Hi, sorry for the delayed response. Hope this helps you integrate my IF stage into your project.

In short, you need to take the modules present in my IF stage and make sure my interface is compatible with yours (change one if needed). 

The high-level module taking everything together in the IF stage is at `modules/pipeStages/IFStage.v`. It uses the following modules:

- `modules/memoryModules/instructionMem.v`
- `modules/mux.v` (the `mux` modules not the `mux_3input`)
- `modules/register.v`
- `modules/adder.v`

**NOTE!** that parameters `WORD_LEN`, `INSTR_MEM_SIZE`, and `MEM_CELL_SIZE` present in these files are imported from the `defines.v` file. You can either use such file or just provide some constants; your choice... However, it makes the project significantly cleaner and reduce the chance of bugs to have all constants in a central place. I highly suggest using such file in your project.

**IMPORTANT NOTE**
The high-level module has an interface as follows:
```
module IFStage (clk, rst, brTaken, brOffset, freeze, PC, instruction);
  input clk, rst, brTaken, freeze;
  input [`WORD_LEN-1:0] brOffset;
  output [`WORD_LEN-1:0] PC, instruction;
```
The `PC` and `instruction` signals are passed on to the next stage (register between IF and ID).  `brTaken` and `brOffset` should be there if you have a branch detection unit in the first place. The `freeze` signal has to do with a hazard detection unit. Do take a look at the diagram in README. **You need to make sure that these signals match your interface.**
